plugins {
    id 'base'
}

allprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://maven.tterrag.com/' }
        maven { url = 'https://maven.createmod.net' }
        maven { url = 'https://maven.ithundxr.dev/mirror' }
        maven { url = 'https://maven.blamejared.com' }
        maven { url = 'https://cursemaven.com' }
        maven { url = 'https://modmaven.dev/' }
        maven { url = 'https://jitpack.io' }
        maven { url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/' }
    }
}

subprojects {
}