import java.time.Instant

plugins {
    id 'base'
}

allprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url = 'https://maven.parchmentmc.org' }
        maven { url = 'https://maven.tterrag.com/' }
        maven { url = 'https://maven.createmod.net' }
        maven { url = 'https://maven.ithundxr.dev/mirror' }
        maven { url = 'https://maven.blamejared.com' }
        maven { url = 'https://cursemaven.com' }
        maven { url = 'https://modmaven.dev/' }
        maven { url = 'https://jitpack.io' }
        maven { url = 'https://raw.githubusercontent.com/Fuzss/modresources/main/maven/' }
    }
}

subprojects {
    plugins.withType(JavaPlugin).configureEach {
        // This block of code expands all declared replace properties in the specified resource targets.
        // A missing property will result in an error. Properties are expanded using ${} Groovy notation.
        // When "copyIdeResources" is enabled, this will also run before the game launches in IDE environments.
        // See https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html
        tasks.named("processResources", ProcessResources).configure {
            var replaceProperties = [
                    minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
                    forge_version       : forge_version, forge_version_range: forge_version_range,
                    loader_version_range: loader_version_range,
                    mod_id              : mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
                    mod_authors         : mod_authors, mod_description: mod_description,
            ]
            inputs.properties replaceProperties

            filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
                expand replaceProperties + [project: project]
            }
        }


        sourceSets {
            main {
                resources {
                    srcDir 'src/generated/resources'
                }
            }
        }

        tasks.withType(ProcessResources).configureEach {
            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        }


    }

    tasks.matching { it.name.contains("jarJar") }.configureEach {
        version += "-git-" + 'git rev-parse --short HEAD'.execute().text.trim() +
                "-t" + Instant.now().toString().replace(':', '-')

        archiveBaseName = "extended-signals-${project.name}"
    }
}

tasks.register("copyAllJars", Copy) {
    dependsOn subprojects.collect { sub ->
        sub.tasks.matching { task ->
            task.name.toLowerCase().contains("jarjar")
        }
    }

    from(subprojects.collect { it.layout.buildDirectory.dir("libs") }) {
        include "*-all.jar"
    }

    into layout.projectDirectory.dir("output")
}

tasks.named("build") {
    finalizedBy("copyAllJars")
}